import { Module } from './module'

export const MODULES: Module[] = [
  { 
    id: 1, 
    code: 'CS1010', 
    modName: 'Programming Methodology', 
    modCredits: 4, 
    professor: 'TAN SOON HUAT, GARY', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 2, 
    code: 'CS1020', 
    modName: 'Data Structures and Algorithms I', 
    modCredits: 4, 
    professor: 'LOW KOK LIM', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 3, 
    code: 'CS1101S', 
    modName: 'Programming Methodology', 
    modCredits: 5, 
    professor: 'HENZ, MARTIN', 
    lastTaught: 'AY2016/2017 SEM 1', 
    lastReviewed: '1/1/2017', 
  },
  { 
    id: 4, 
    code: 'CS1231', 
    modName: 'Discrete Structures', 
    modCredits: 4, 
    professor: 'TAN TUCK CHOY, AARON', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 5, 
    code: 'CS2010', 
    modName: 'Data Structures and Algorithms II', 
    modCredits: 4, 
    professor: 'CHONG KET FAH', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 6, 
    code: 'CS2030', 
    modName: 'Programming Methodology II', 
    modCredits: 4, 
    professor: 'OOI WEI TSANG', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 7, 
    code: 'CS2040', 
    modName: 'Data Structures and Algorithms', 
    modCredits: 4, 
    professor: 'SOH SOON HONG, HAROLD', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { id: 8, 
    code: 'CS2100', 
    modName: 'Computer Organisation', 
    modCredits: 4, 
    professor: 'WONG WENG FAI\nSUPPIAH, RAVI', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 9, 
    code: 'CS2101', 
    modName: 'Effective Communication for Computing Professionals', 
    modCredits: 4, 
    professor: 'EXTERNAL', 
    lastTaught: 'NOT APPLICABLE', 
    lastReviewed: '1/1/2017',
  },
  { 
    id: 10, 
    code: 'CS2103', 
    modName: 'Software Engineering', 
    modCredits: 4, 
    professor: 'LEE MONG LI, JANICE\nBRESSAN, STEPHANE', 
    lastTaught: 'AY2016/2017 SEM 2', 
    lastReviewed: '1/1/2017',
  },
];