import { Module } from './module'

export const MODULES: Module[] = [
  //{ 
  //   id: 1, 
  //   code: 'CS1010', 
  //   modName: 'Programming Methodology', 
  //   //modCredits: 4, 
  //   //professor: 'TAN SOON HUAT, GARY', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '3/5/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 58,
  //   teachingRating: 3,
  //   enjoyabilityRating: 3,
  //   difficultyRating: 3,
  //   workloadRating: 3
  // },
  // { 
  //   id: 2, 
  //   code: 'CS1020', 
  //   modName: 'Data Structures and Algorithms I', 
  //   //modCredits: 4, 
  //   //professor: 'LOW KOK LIM', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '31/8/2017',
  //   overallVerdict: 'not-recommend',
  //   percentageRecommend: 22,
  //   teachingRating: 1,
  //   enjoyabilityRating: 2,
  //   difficultyRating: 4,
  //   workloadRating: 4
  // },
  // { 
  //   id: 3, 
  //   code: 'CS1101S', 
  //   modName: 'Programming Methodology', 
  //   //modCredits: 5, 
  //   //professor: 'HENZ, MARTIN', 
  //   //lastTaught: 'AY2016/2017 SEM 1', 
  //   description: "",
  //   lastReviewed: '1/1/2017', 
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 82,
  //   teachingRating: 4,
  //   enjoyabilityRating: 4,
  //   difficultyRating: 5,
  //   workloadRating: 5
  // },
  // { 
  //   id: 4, 
  //   code: 'CS1231', 
  //   modName: 'Discrete Structures', 
  //   //modCredits: 4, 
  //   //professor: 'TAN TUCK CHOY, AARON', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '24/7/2017',
  //   overallVerdict: 'not-recommend',
  //   percentageRecommend: 46,
  //   teachingRating: 3,
  //   enjoyabilityRating: 3,
  //   difficultyRating: 3,
  //   workloadRating: 3
  // },
  // { 
  //   id: 5, 
  //   code: 'CS2010', 
  //   modName: 'Data Structures and Algorithms II', 
  //   //modCredits: 4, 
  //   //professor: 'CHONG KET FAH', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '23/6/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 74,
  //   teachingRating: 4,
  //   enjoyabilityRating: 4,
  //   difficultyRating: 5,
  //   workloadRating: 5
  // },
  // { 
  //   id: 6, 
  //   code: 'CS2030', 
  //   modName: 'Programming Methodology II', 
  //   //modCredits: 4, 
  //   //professor: 'OOI WEI TSANG', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '18/9/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 93,
  //   teachingRating: 5,
  //   enjoyabilityRating: 5,
  //   difficultyRating: 5,
  //   workloadRating: 5
  // },
  // { 
  //   id: 7, 
  //   code: 'CS2040', 
  //   modName: 'Data Structures and Algorithms', 
  //   //modCredits: 4, 
  //   //professor: 'SOH SOON HONG, HAROLD', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '27/10/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 83,
  //   teachingRating: 4,
  //   enjoyabilityRating: 4,
  //   difficultyRating: 4,
  //   workloadRating: 4
  // },
  // { id: 8, 
  //   code: 'CS2100', 
  //   modName: 'Computer Organisation', 
  //   //modCredits: 4, 
  //   //professor: 'WONG WENG FAI\nSUPPIAH, RAVI', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '1/1/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 58,
  //   teachingRating: 3,
  //   enjoyabilityRating: 3,
  //   difficultyRating: 3,
  //   workloadRating: 3
  // },
  // { 
  //   id: 9, 
  //   code: 'CS2101', 
  //   modName: 'Effective Communication for Computing Professionals', 
  //   //modCredits: 4, 
  //   //professor: 'EXTERNAL', 
  //   //lastTaught: 'NOT APPLICABLE', 
  //   description: "",
  //   lastReviewed: '1/1/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 58,
  //   teachingRating: 3,
  //   enjoyabilityRating: 3,
  //   difficultyRating: 3,
  //   workloadRating: 3
  // },
  // { 
  //   id: 10, 
  //   code: 'CS2103', 
  //   modName: 'Software Engineering', 
  //   //modCredits: 4, 
  //   //professor: 'LEE MONG LI, JANICE\nBRESSAN, STEPHANE', 
  //   //lastTaught: 'AY2016/2017 SEM 2', 
  //   description: "",
  //   lastReviewed: '1/1/2017',
  //   overallVerdict: 'recommend',
  //   percentageRecommend: 58,
  //   teachingRating: 3,
  //   enjoyabilityRating: 3,
  //   difficultyRating: 3,
  //   workloadRating: 3
  // },
];